// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXxkJbpj6VtCYBkiBQk5_LvzK_u5TL2N8',
    appId: '1:658748476499:web:4f09089fb6edd0162acaa6',
    messagingSenderId: '658748476499',
    projectId: 'mytodo-10248',
    authDomain: 'mytodo-10248.firebaseapp.com',
    storageBucket: 'mytodo-10248.appspot.com',
    measurementId: 'G-96JVJXJY7J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Cy1gYcZlwSVp2dvGCqMdQ9yAirRGkX0',
    appId: '1:658748476499:android:d63bfe4a83ed30592acaa6',
    messagingSenderId: '658748476499',
    projectId: 'mytodo-10248',
    storageBucket: 'mytodo-10248.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBi7dZF2lpBiYxEeFebaQaA8mviI6SuDmk',
    appId: '1:658748476499:ios:f0b8fa7b3e2858812acaa6',
    messagingSenderId: '658748476499',
    projectId: 'mytodo-10248',
    storageBucket: 'mytodo-10248.appspot.com',
    iosBundleId: 'com.example.fireTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBi7dZF2lpBiYxEeFebaQaA8mviI6SuDmk',
    appId: '1:658748476499:ios:f0b8fa7b3e2858812acaa6',
    messagingSenderId: '658748476499',
    projectId: 'mytodo-10248',
    storageBucket: 'mytodo-10248.appspot.com',
    iosBundleId: 'com.example.fireTodo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXxkJbpj6VtCYBkiBQk5_LvzK_u5TL2N8',
    appId: '1:658748476499:web:52ac9e94d81bb8682acaa6',
    messagingSenderId: '658748476499',
    projectId: 'mytodo-10248',
    authDomain: 'mytodo-10248.firebaseapp.com',
    storageBucket: 'mytodo-10248.appspot.com',
    measurementId: 'G-KE2SV6XCGY',
  );
}
